from enum import StrEnum


class ResponseStatus(StrEnum):
    SUCCESS = 'SUCCESS'
    ERROR = 'ERROR'


class ResponseCode(StrEnum):
    SUCCESS = 'SUCCESS'
    SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG'

    VERIFICATION_MAIL_SENT = 'VERIFICATION_MAIL_SENT'
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'
    EMAIL_DOES_NOT_EXISTS = 'EMAIL_DOES_NOT_EXISTS'
    EMAIL_NOT_PROPER = 'EMAIL_NOT_PROPER'

    EMAIL_VERIFIED = 'EMAIL_VERIFIED'
    BAD_SIGNATURE = 'BAD_SIGNATURE'

    NAME_TOO_SHORT = 'NAME_TOO_SHORT'

    DISPLAY_NAME_TOO_SHORT = 'DISPLAY_NAME_TOO_SHORT'

    PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT'
    PASSWORD_PATTERN_NOT_MATCHED = 'PASSWORD_PATTERN_NOT_MATCHED'
    PASSWORD_INCORRECT = 'PASSWORD_INCORRECT'

    LOGGED_IN = 'LOGGED_IN'
    LOGGED_OUT = 'LOGGED_OUT'
    NOT_LOGGED_IN = 'NOT_LOGGED_IN'
